services:
  api_service:
    build: ./api
    container_name: api_service
    ports:
      - "4000:80"

  rubyapi_service:
    build: ./rubyapi
    container_name: rubyapi_service
    ports:
      - "3000:80"
  portfolio:
    build: ./andrewnzioki
    container_name: portfolio
    ports:
      - "8000:80"
